{{- if not .Values.tcpExternalConfig}}
{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx-ingress.tcp-configmap" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  22: "{{ .Release.Namespace }}/{{ template "fullname" . }}:{{ .Values.service.externalPort }}"
{{- end -}}
{{- end -}}
