{{- if .Values.enabled }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "redis-ha.serviceAccountName" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
{{- end -}}
{{- end -}}
