{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "name" . }}
    role: service
{{ include "gitlab.standardLabels" . | indent 4 }}
  name: {{ template "fullname" . }}-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-role: "sentinel"
{{ include "gitlab.standardLabels" . | indent 4 }}
{{- end -}}
