---
- name: Install kubectl and cert utils
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Download cfssl
      get_url:
        url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
        dest: /usr/local/bin/cfssl
        mode: 0755
# cfssl version
# Version: 1.2.0

    - name: Download cfssljson
      get_url:
        url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
        dest: /usr/local/bin/cfssljson
        mode: 0755

    - name: Download kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 755
#  kubectl version --client  version 1.10.2
