{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
    component: "{{ .Values.controller.name }}"
  name: {{ template "nginx-ingress.controller.fullname" . }}
data:
  enable-vts-status: "{{ .Values.controller.stats.enabled }}"
{{- if .Values.controller.headers }}
  proxy-set-headers: {{ .Release.Namespace }}/{{ template "nginx-ingress.fullname" . }}-custom-headers
{{- end }}
{{- if .Values.controller.config }}
{{ toYaml .Values.controller.config | indent 2 }}
{{- end }}
{{- end }}
