{{- if .Values.enabled -}}
{{- if .Values.controller.headers }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
    component: "{{ .Values.controller.name }}"
  name: {{ template "nginx-ingress.fullname" . }}-custom-headers
data:
{{ toYaml .Values.controller.headers | indent 2 }}
{{- end }}
{{- end }}
