{{- if .Values.enabled -}}
{{- if or .Values.rbac.create .Values.rbac.createRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
  name: {{ template "nginx-ingress.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "nginx-ingress.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nginx-ingress.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
