{{- if .Values.enabled -}}
{{- if or .Values.rbac.create .Values.rbac.createRole .Values.rbac.createClusterRole -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
  name: {{ template "nginx-ingress.fullname" . }}
{{- end -}}
{{- end -}}
