{{- if .Values.enabled -}}
{{- if and .Values.tcp (not .Values.tcpExternalConfig) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
    component: "{{ .Values.controller.name }}"
  name: {{ template "nginx-ingress.tcp-configmap" . }}
data:
{{ toYaml .Values.tcp | indent 2 }}
{{- end }}
{{- end }}
