---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "engine.fullname" . }}
  labels:
    app: crawler
    component: engine
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: engine
      release: {{ .Release.Name }}
  template:
    metadata:
      name: engine
      labels:
        app: crawler
        component: engine
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: engine
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: engine
          protocol: TCP
        env:
        - name: ENGINE_DATABASE_HOST
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
